### PR TITLE
Add russian Translations

### PR DESCRIPTION
**Pull request by vitalii2011**

### CODE REVIEW

**Comment by tn4799** [comment]
If you add russian translations please also add a russian description. Otherwise it would not be compatible with the modhub guidelines

**Comment by vitalii2011** [comment]
> If you add russian translations please also add a russian description. Otherwise it would not be compatible with the modhub guidelines

```
        <ru>
<![CDATA[Этот мод добавляет в игру контракты на прикатывание. Контракт на прикатывание может сгенерироваться после того, как поле было засеяно.
Вы заработаете около 700 $ с гектара поля.
            
Примечание:
Поскольку контракты на прикатывание имеют некоторые общие свойства генерации с контрактами на внесение удобрений, эти две миссии работают друг против друга при генерации. Так что не ожидайте, что вы всегда будете получать контракт на прикатывание. Какой из них будет сгенерирован, определяется случайным образом.

Для запросов поддержки и улучшения, пожалуйста, откройте вопрос на <a href="https://github.com/tn4799/RollerMission/issues">Github</a>.]]></ru>
``` 

<description> was left without translation into Russian because only en, de, fr and pl are supported on ModHub and the description of the mod in the game; when choosing any other localization of the game, there will be a description option in English (most often).
That is, adding a translation into any other language other than en, de, fr and pl in <description> is superfluous.

**Comment by tn4799** [comment]
I've merged it manually with a couple of little changes.

**Comment by vitalii2011** [comment]
> I've merged it manually with a couple of little changes.

It is better to have no translation into Russian at all than such an option - as if a half-educated student substituted the first versions of the translation of the words offered by the dictionary, depriving the text of meaning. Now it’s hard to guess what it’s about, it’s better to let the default English version be shown.

**Comment by tn4799** [comment]
Ive checked your translations with DeepL and the word roller mission, or in german walzmissionen didnt show how i thought so i changed those words. 
But I am open to feedback. I`m not perfect and i make mistakes. Please add your description translation into the modDesc.xml and then i will undo my last commit and merge your PR.

**Comment by vitalii2011** [comment]
> Ive checked your translations with DeepL and the word roller mission, or in german walzmissionen didnt show how i thought so i changed those words. But I am open to feedback. I`m not perfect and i make mistakes. Please add your description translation into the modDesc.xml and then i will undo my last commit and merge your PR.

Machine translation does ignore (yet) context. 
Try to translate (using DeepL or a similar service) a phrase in your language into any other, and then back to yours, and most likely, you will understand what I mean.
The localization of the Giants correctly named "Прикатывание
fsScreen_2022_10_25_16_26_20
".

**Comment by tn4799** [comment]
> What is it in modDesc.xml? Screenshot 2022-10-25 at 19-16-24 Update modDesc xml by vitalii2011 · Pull Request #3 · tn4799_RollerMission

That only was there accidentally.

**Pull request closed without merging**
